### ISSUE TITLE
GeoIP fails due to certificate issue

### ISSUE THREAD

**Issue by CubicrootXYZ** [woblerr/authlog_exporter#2]
Installation method: docker (ghcr.io image)
Version: latest (it actually is already a few days old once I pulled it)

## Expected behavior

The geo data resolving is working.

## Actual behavior

Unfortunately getting geo data for IPs fails for the `url` method using `freegeoip.live` fails with this error in the logs:

```
level=error ts=2022-10-24T13:00:58.462Z caller=geo.go:89 msg="Error getting GeoIp URL" err="Get \"https://freegeoip.live/json/xxxxxxxxx\": x509: certificate signed by unknown authority"
```
## Possible solution

This probably happens due to the missing `ca-certificates` package in the image. Adding this to the `Dockerfile` should add them: 
```
RUN apk add --no-cache ca-certificates && update-ca-certificates
```

If you want me to open a MR with the fix I will do so once I am having time for it.

**Comment by woblerr** [comment]
Hi,
Thanks, yes, there is an error.

I'll fix it soon.

**Comment by woblerr** [comment]
@CubicrootXYZ 
It should be fixed now.
